title:            Taekyung Kim's Homepage
description:      #Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //tkkim93.github.io
#http://localhost:5000
#https://tkkim93.github.io
disqus_shortname: tkkim93

# Owner/author information
owner:
  name:           Taekyung Kim
  avatar:         profile.jpg
  bio:            PhD student @ Computer Intelligence Lab, KAIST
  email:          tkkim93@kaist.ac.kr
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
#  twitter: ''
  linkedin: taekyung-kim-a42607187
  google_scholar: sRab1k8AAAAJ
#  google_plus: ''
  github: tkkim93
# Analytics and webmaster tools stuff goes here
google_analytics: UA-52736040-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /aboutme/
  - title: Publications
    url: /publications/
  - title: Teaching & Service
    url: /service/
  - title: <a href="https://drive.google.com/open?id=1vd6QiZ707l48IJGBGWlgRNbXO4G_b2iR">CV</a>
#    url: 

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Zurich
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
